### ISSUE TITLE
Suggestion: Threshold becomes a configurable setting

### ISSUE THREAD

**Issue by ash-lewis** [theirstory/gliner-spacy#1]
I noticed that on the original gliner_base model Threshold is a configurable setting, is it possible to add Threshold to our list of configurable properties?

Cool project!

**Comment by wjbmattingly** [comment]
Thanks so much for this @ash-lewis ! And thanks for your interest. I think this is a great idea. I'll try and get that update ready in the next few days.

**Comment by wjbmattingly** [comment]
You can now use 

```bash
pip install gliner-spacy --upgrade
```

This will upgrade you to 0.0.3 which now allows you to set the threshold.
