### ISSUE TITLE
Gliner-spacy package version 0.0.9 throws `ModuleNotFoundError: No module named 'seaborn'`

### ISSUE THREAD

**Issue by eriknovak** [theirstory/gliner-spacy#22]
If `gliner-spacy==0.0.9` is installed, components that use the `spacy` package throw `ModuleNotFoundError: No module named 'seaborn'` regardless of whether the component uses `gliner-spacy` or not.

This error does not appear when using `gliner-spacy==0.0.8`.

**Comment by wjbmattingly** [comment]
Oh no! Thanks for catching that. I didn't update my setup.py. I've fixed it and version 0.0.10 should resolve this issue.
