### ISSUE TITLE
`gliner_spacy.__version__` not defined

### ISSUE THREAD

**Issue by davidggphy** [theirstory/gliner-spacy#8]
It raises AttributeError: module 'gliner_spacy' has no attribute '__version__'

Code to replicate:
```python
import gliner
import spacy
import gliner_spacy

print(f"{spacy.__version__=}")
print(f"{gliner.__version__=}")
print(f"{gliner_spacy.__version__=}")
```

**Comment by wjbmattingly** [comment]
Thanks for catching this! I have fixed it with v. 0.0.6: https://github.com/theirstory/gliner-spacy/commit/3def6b5cfac212554452c8579107e5a4c6a4a5c5
